# Generated by Django 3.2 on 2023-11-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csv_file_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniqueIdentifier', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('ReportsTo', models.CharField(max_length=200)),
                ('Designation', models.CharField(max_length=200)),
            ],
        ),
    ]
