# Generated by Django 3.2 on 2023-11-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='csv_file_data',
            new_name='csvfiledata',
        ),
    ]
