# Generated by Django 3.2 on 2023-11-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_csv_file_data_csvfiledata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='csvfiledata',
            new_name='EmployeeList',
        ),
    ]
